name: compile_and_test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build & test game on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [ g++-14 ]
        include:
          - os: ubuntu-latest
            compiler: g++-14
            target: Linux

          - os: macos-latest
            compiler: g++-14
            target: Macos

          - os: windows-latest
            compiler: cl
            target: Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Compile a Build for game
        run: ./scripts/compile.sh \
            --cpp-compiler ${{ matrix.compiler }} \
            --os ${{ matrix.target }}

      - name: Run all of Tests.
        run: ./scripts/test.sh