name: compile_and_test

on:
  push:
    branches: [ main,sonarqubeSetup ]

  pull_request:
    branches: [ main,sonarqubeSetup ]

  workflow_dispatch:

defaults:
  run:
    shell: bash
permissions:
  contents: write
jobs:
  build_and_test:
    name: Build & test game on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [ g++-14 ]
        include:
          - os: ubuntu-latest
            compiler: g++-14
            target: Linux

          - os: windows-latest
            compiler: cl
            target: Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install build dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++-14 cmake ninja-build

      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Compile a Build for game
        run: ./scripts/compile.sh ${{ matrix.compiler }} ${{ matrix.target }}

      - name: Run all of Tests.
        run: ./scripts/test.sh
  coverage:
    name: Coverage report on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++-14 cmake ninja-build python3-pip
          pip install gcovr
      - name: Install Sonar build-wrapper
        run: |
          curl -sSLo build-wrapper.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper.zip


      - name: Build with wrapper (FULL clean build)
        run: |
          ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 \
            --out-dir bw-output \
            bash -c "
              rm -rf build-coverage &&
              cmake -S . -B build-coverage -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER=g++-14 &&
              cmake --build build-coverage
            "
      - name: Run tests
        run: ctest --test-dir build-coverage --output-on-failure

      - name: Generate coverage report
        run: |
          gcovr \
            --root . \
            --object-directory build-coverage \
            --filter src/ \
            --exclude ".*dummy\.cpp" \
            --sonarqube coverage.xml
      - name: Debug compile_commands paths
        run: |
          echo "Runner pwd: $(pwd)"
          head -5 build-coverage/compile_commands.json
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the SonarScanner CLI
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=ACPP-Team04_rpg04
            -Dsonar.organization=acpp-team04
            -Dsonar.sources=src/main
            -Dsonar.tests=src/test
            -Dsonar.coverageReportPaths=coverage.xml
            -Dsonar.cfamily.build-wrapper-output=bw-output
            # Comma-separated paths to directories containing main source files.
            #-Dsonar.sources= # optional, default is project base directory
            # Comma-separated paths to directories containing test source files.
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
          # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
          #-Dsonar.verbose= # optional, default is false
          # When you need the analysis to take place in a directory other than the one from which it was launched, default is .
          projectBaseDir: .